### ISSUE TITLE
Mise en forme des objets

### ISSUE THREAD

**Issue by guigail** [sallaire/jsickbeard#2]
Définir un objet type avec héritage pour la définition des données. 
Exemple : 
tvshows : [ {id, name, date, _isFollow_, **season** : [ 
     { number, name, date, **episodes** : [ 
          { number, name, date, quality, ... } ] } ] } ]

(isFollow : flag permettant de savoir si la série est suivi ou non)

Le but étant de récupérer la même architecture de données plutot que d'avoir d'un coté un objet metadata et de l'autre tvshow et uniformiser les attributs de ceux ci.

Ce qui permet de découper les informations et les récupérer avec des services tel que : 

- **/tvshows?name&lang**  (Recherche de toutes les séries, même celle suivie)
- **/tvshows/:id** (Accès à une série complète "suivie")
- **/tvshows/:id/saison/:number** (Accès à une saison et ses épisodes)
- **/tvshows/:id/saison/:number/episodes/:number** (Accès à un épisode)

**Comment by sallaire** [comment]
C'est fait : https://github.com/sallaire/jsickbeard/commit/dab6fd970085976f07503c223744e904cc60fcef
